### ISSUE TITLE
User Feedback 2024_09_18 AG

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#180]
# Login 

- [ ] Mail field is not autocomplete in login with Passbolt 
- [x] Pas de fonctionnalité de mot de passe oublié 

# Splash screen 
Footer avec le logo des financeurs

# https://arvest-dev.tetras-libre.fr/app/my-projects (lists)

- [x] No tooltip on left menu icon
- [x] No placeholder on create project footer form 
![Image](https://github.com/user-attachments/assets/edc82cd5-62d3-463a-8324-bd863d48f917)
- [x] Enter dont submit the project form
- [x] No focus on the input after clicking on the + button
- [x] Search in project is not intuitive. I expect list change on every input
- [x] "Search projects" --> Filter projects (without maj P)
- [x] Long project tittle caused display glitch   (word wrap with tooltip that display entire title)
![Image](https://github.com/user-attachments/assets/8a35169f-ade0-4baf-8719-649eed3f7dfc)
![Image](https://github.com/user-attachments/assets/2ad303a8-df0e-48bf-aaaf-241495244cb7)
![Image](https://github.com/user-attachments/assets/dc4e7ccb-8c06-4479-8355-696b10e1ad89)
- [x] C'est quoi la preview d'un projet : Use the first manifest's thumbnail and the next one if there is no first etc... if there is none placeholder. User can overide this thumbnail with a custom image from his medias or from the entire web.
- [x] Implement Mirador Font everythere

- [x] J'aimerais avoir plus d'infos sur le projet (createur, last saved creation date ) 
- [ ] Let the user "OrderBy" update / name / creator /createdAt

# https://arvest-dev.tetras-libre.fr/app/my-projects (project displayed)

- [x] Title of project is written in strange policy. 
I would like something like in Mirador
![Image](https://github.com/user-attachments/assets/29d9b580-3d7d-4efb-8a9f-245ad304bb10)

- [x] Title must be removed from top and implement in the right side panel with a separator above "save project"
- [x] Save button is difficult to see/find.
- [x] Difficult to comeback to the list from Project display to project list 
- [x] Save Mirador --> Save project 
- [x] Mirador pourrait descendre jusqu'en bas de l'écran
![Image](https://github.com/user-attachments/assets/b6bec095-7bc5-4438-9d30-be023bc38c1e)
- [x] Glitch affichage avec le menu ouvert
![Image](https://github.com/user-attachments/assets/6f644f43-8ffe-4591-86cf-6c99e651cf2d)
- [x] Au save je préferais le toast "project tartanpion saved" plutot que "project saved" 

# Edit property modal

[ ] L'input de description de projet est trop étroit et je m'attendrais à avoir un textarea et non un input text
- [x] L'édition des champs demande trop de clic
   - [x] Je préférerais tous les champs dans des inputs et un save globale
- [x] Pas de tooltip sur les élements
- [x] Pas de placeholder sur le search en éditant un media 
![Image](https://github.com/user-attachments/assets/ea5a1d83-3cce-4fe4-a937-55f7288de293)

- [x] J'aimerais une petite infobulle (ou autre) à coté d'Access List expliquant la différence admin editor reader. A adapter selon le type d'édition (project media manifest) un petit point d'intérogation a côté de "Access List" qui explique les droits
- [x] Access list should be rename into "Permissions"
- [x] Placeholder of Search input should be "Search user or group"
- [x] Input d'ajout d'user sous le title Access List
![Image](https://github.com/user-attachments/assets/3457db33-8b92-4abf-a017-c886a794b017)

- [x] "Delete item" --> "delete project" (ou media manifest selon les cas)
- [x] "Access list" --> "User access list"
- [x] Je dois pouvoir rechercher uniquement par username (le username et les usergroups name doivent être UNQUE en BD, il faut donc handle cette erreur à la création de user/de groupe)
- [x] Espace incohérent entre les différent éléments

# Général 
- [x] Searched must be sticky at top 
- [x] J'ai du mal à savoir dans quel univers je suis (projects , manifest par exemple)
- [x] username est ce vraiment utile ?
- [x] La police d'arvest semble différent de Mirador  
Mirador 
![Image](https://github.com/user-attachments/assets/cf88e436-7303-4c21-8299-c4aad8254148)

![Image](https://github.com/user-attachments/assets/12a7947d-55f1-4c3b-b6cf-9a54db85683c)
Arvest 
![Image](https://github.com/user-attachments/assets/f5a0e53b-97ed-4324-ba9c-94df21f01287)
- [x] Le menu de gauche doit être ouvert par défaut
- [x] Les items du menu de gauche doivent être bien en bas du panel
- [x] Pagination must be sticky at top

# Gestion manifest 

- [x] L'universt manifest n'est pas grisé quand sélectionné
![Image](https://github.com/user-attachments/assets/80ac3255-b31a-4099-9e92-c38600e22ec4)
- [x] Recherche de manifest idem que décrit dans projet
- [x] Message "Vous n'avez aucun manifest" 
- [x]  "Search Manifest" --> "Search manifests"
- [x] Le menu en bas à droite est pertubant. Il fonctionne en mouse over et non click comme les autres. Du coup si j'arrive sur le + et clic vite, le menu s'ouvre et se referme, retirer le mouse hover.
- [ ] Implémenter la logique qui permet d'avoir un thumbnail pour les manifests : 
- [ ] Implementer un champs "Origin" en BD. (Create, Upload, Link) : Associer à un badge dans le rendu en front
- [ ] lorsque je fetch un manifest il faut un element d'UI qui affiche le fait que l'URL est dead
- [ ] Pagination dans les listes 10 élements 
- [ ] Petit bouton oeil qui permet de visualiser le manifest dans mirador sans le plugin edition

# Création manifest 

- [x] Il y a un bouton back to manifests à priori inutile il faut que quand on qui
- [x] Remove the "+" button when in creation Manifest
- [ ] Lorsque l'utilisateur ajoute un Media, on regarde en BD si ce Media existe : 
        - si ce Media existe : On utilise le Thumbnail Url associé à ce Media 
        - si ce Media n'existe pas : On créer un nouveau Media 'Link' depuis l'exterieur en BD et on créé le Thumnail associé à ce média qu'on utilise dans le Manifest  
- [ ] Lorsque l'utilisateur colle le lien d'un Media il faut qu'il y est une preview de cette image 
- [x] Le panel de média à droite devrait s’ouvrir dès que l'on a un canvas
- [ ] J'aimerais qu'à l'ajout d'un media, arvest m'affiche une petite preview qui me confirmerais que le media est bien trouvé et qui me permettra de m'y retrouver lorsque j'aurais de nombreux canvas et media en meme temps 
- [x] Remove field --> Remove media 
- [x] Bouton add media to canvas 1 et remove Canvas 1 sur la même ligne  
- [x] Lorsque je clic sur Create il ne se passe rien et le manifest n'est pas créé. Edit : ah non il faut F5 en fait 
- [x] Je peux créer un manifest sans canvas (Bouton create devrait être disabled)
- [ ] J'aimerais pouvoir drag and drop mon media dans un champ 
- [x] Le placeholder d'un média n'est pas compréhensible, ça devrait être "Media URL"

# Gestion media (liste)

- [x] Pour la cohérence je m'attendrais à avoir un "+ add media" en bas à droite plutot qu'un bouton upload media en haut à gauche
- [ ] J'aimerais pouvoir preview une image en cliquant sur celle ci dans la liste 
- [x] Recherche de manifest idem que décrit dans projet
- [ ] PAs de message d'erreur si j'essaie d'upload un fichier non image, exempel un pdf
- [ ] Implementer un champs "Origin" en BD. (Create, Upload, Link) : Associer à un badge dans le rendu en front
- [x] Quand le titre du Media est trop long le texte sort de la modal de confirmation de suppression 
# Gestion groupe 

- [ ] Bouton oeil qui permet de visualiser les membres du groupe

**Comment by Drilio** [comment]
1) Mirador FullScreen
2) Modal Edition 
3) General Ui Stuff qui prennent pas 1000 ans
