### ISSUE TITLE
User feedback Daxid

### ISSUE THREAD

**Issue by daxid** [SCENE-CE/mirador-multi-user#183]
- [ ] Delete user group is not working on xema
- [x] Share media with user as Reader still allow user to edit media
- [ ] Groups does not appear to share media
- [ ] Filtering lists is case dependent
- [ ] Filtering lists is not considering sub-strings
- [ ] Created manifests are "empty" when opened in mirador
- [ ] Tooltip prevent from clicking left menu item
![image](https://github.com/user-attachments/assets/69c5e7d7-9511-473e-9573-0f6760530dd8)

**Comment by Drilio** [comment]
what do you mean by " Created manifests are "empty" when opened in mirador" ?

**Comment by daxid** [comment]
When you create a manifest with an image in the app and open it in Mirador, nothing appears (only grey).

I did not try to reproduce. I think this deserves a dedicated issue. I'll test it more tomorrow.

**Comment by Drilio** [comment]
![image](https://github.com/user-attachments/assets/5bdce344-fdd2-43e3-ba8a-2a78dd4db2a0)
Is this an example ?

**Comment by geourjoa** [comment]
@Drilio @daxid 

I dont know if task mentionned here are always relevant

**Comment by daxid** [comment]
I think it has been fixed along the way
