### ISSUE TITLE
Fix thumbnail issues

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#188]
- [x] When we upload media, we must generate thumbnail on the upload 
- [x] When we link external media in allMedias, we must generate thumbnail and create associated folder on the filesystem
- [x] When create Manifest 
    - [x] Add field thumbnail URL for the manifest 
    - [x] If the URL come from Arvest backend, add the  _thumbnail suffix
    - [x] Else use the given URL and trigger warning if media is more than XSize (Xsize is in .env)
    - [x] Add preview aside to thumbnail field 
 - [x] Media side panel
     - [x] The medias displayed are not the true media but the preview
     - [x] Add possibilty to upload media directly from the side panel
     - [x] Add possibilité to link media directly from the side panel
 - [x] When edit project, add the possibility to add thumbail. You must use right panel to to that

**Comment by geourjoa** [comment]
TODO

**Comment by Drilio** [comment]
- [ ] Fix error on manifest creation submit create after implementing the thumbnail into manifest creation
