### ISSUE TITLE
Add account confirmation

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#218]
We need to avoid unwanted account creation on MMU

Use a captcha without using third parties (self hosted or commercial product). 

https://www.npmjs.com/package/react-simple-captcha can be the good package

**Comment by Drilio** [comment]
I just looked at the way it adapt to react 18 and typescript, it looks like a really ugly way to implement a captcha now,  the package don't use modern react syntax and the way we have to adapt to use it with typescript isn't "straight forward". 

 I'll check if there is a better package.

**Comment by Drilio** [comment]
We need to test it on test server because there API bloc Captcha.
source : https://docs.hcaptcha.com/

**Comment by geourjoa** [comment]
> https://github.com/hCaptcha/react-hcaptcha this package seems more accurate :
> 
>     * Recent updates
> 
>     * Compatible with TS and react18
> 
>     * More star on github

You need third party when using this package. @daxid What do you think of that ?

**Comment by daxid** [comment]
We decide to use a confirmation email (with link to validate account) instead of a captcha.
