### ISSUE TITLE
[Feedback] Change terminology

### ISSUE THREAD

**Issue by jdchart** [SCENE-CE/mirador-multi-user#252]
- [ ] Change "**Manifests**" to "**Resources**" in all occurences (including main menu, and Manifest creation).

The term Manifest is difficult for users to understand. We hesitated with Document, but feel Resource is the best path (this also adhere's to Mirador's solution -> they ask that the user add "IIIF Resources" rather that Manifests or Collections. This also opens potential for adding IIIF Resources which are of type Collection as well as Manifest.

**Comment by daxid** [comment]
I agree that the word manifest is confusing for newcomers.

However the term resource is very ambiguous. Media are most definitely resources so I would be very confused to se Media beneath Resources  in the left panel.

In the end we will do as you say but we still think that resource is a poor replacement choice for manifest. please note that:

1. In  Mirador context, Resource is not ambiguous, everything is a IIIF resource aka a manifest, but not in MMU
2. We should be able to change the Resource term in Mirador to match what we use in MMU.
3. A collection is a manifest

**Comment by daxid** [comment]
We are keeping the standard IIIF terminology. However all terms can be changed by creation a new translation JSON.

This will be documented in the admin wiki.

I'm closing here
