### ISSUE TITLE
[Feedback] Existing project list

### ISSUE THREAD

**Issue by jdchart** [SCENE-CE/mirador-multi-user#253]
For the list of existing projects that the user has access to: 

- [x] **Edit Project** becomes **Configuration** (change to a gear logo).
- [x] **Open Project** : this should be contextual (**Edit Project** is the user has permission to edit, **Open Project** if the user has permission only to read).
- [x] Inverse the order of these buttons (first Configuration button then the Open Project button).

**Comment by daxid** [comment]
@jdchart Open Project butto  should not be contextual (at least not the way you propose). The buttons that exceed user permissions are greyed. I think this behavior is absolutely correct. We could hide them if you prefer but I don't see a game changer here.

@Drilio Please implement the two other points. As the code is very much factorized, if needed, you can change edit to Configuration and change the pen to a gear logo in all other lists too.
