### ISSUE TITLE
[Feedback] New project creation

### ISSUE THREAD

**Issue by jdchart** [SCENE-CE/mirador-multi-user#254]
- [ ] Currently, when the user creates a new project, they only have the possibility to set the name. We wish that the user clicks on New Project, and instead the Project Configuration pops up (the pop up currently listed as Edit Project, where the user can give name, description, metadata and permissions).

**Comment by daxid** [comment]
@Drilio project creation should open the edition modal, not open the project in Mirador.

Same for groups, we should enter the edition modal, not go back to the list. 

Note : if better for technical reasons (an edition modal may not be opened if the object is not created beforehand), you can ask first for the name like you do now.
