### ISSUE TITLE
Use lastest version of MV and MAEV

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#297]
Lastest stable version (29 Nov)

- MV 1.0.12
- MAE 1.0.36
- MAEV 0.0.12

**Comment by geourjoa** [comment]
@Drilio

**Comment by Drilio** [comment]
![image](https://github.com/user-attachments/assets/b8fc715a-621d-4d37-8039-56d1b4aade8e)
 I fall on this error when I run docker compose up, I tried to remove node_modules and package-lock several times, I also tried to remove the docker container and image et rebuilt it.

**Comment by Drilio** [comment]
Ok I rerun `npm install `on my host machine while docker was up and it works fine. Perhaps some docker cashing issues
