### ISSUE TITLE
CORS when trying to create account

### ISSUE THREAD

**Issue by daxid** [SCENE-CE/mirador-multi-user#30]
![image](https://github.com/SCENE-CE/mirador-multi-user/assets/12066206/48b5744a-e86b-436d-be1c-dfaa74072ad8)

**Comment by daxid** [comment]
@geourjoa 

It may come from the fact that we deployed the front and the backend on different hosts.

**Comment by geourjoa** [comment]
I have fix several problems

- Fixing CORS configuration in backend
- Fixing front end config. 
   - URL Backend was loaded with vite stuff not available in production
