### ISSUE TITLE
2024-12-19 review daxid

### ISSUE THREAD

**Issue by daxid** [SCENE-CE/mirador-multi-user#327]
- [x] Welcome screen image is too large. Yous should lower jpeg quality, and/or lower resolution
- [x] Instead of setting I should see my username
![image](https://github.com/user-attachments/assets/b3515495-3cc9-482f-b547-88d9bed50afc)

- [x] Images are shown as videos in the media panel and in the media tab
![image](https://github.com/user-attachments/assets/e0e927a9-25fc-4fe3-84d6-30afd4643c81)
![image](https://github.com/user-attachments/assets/f31fc6e5-239d-446e-b418-172ed2ca91c0)

- [x] Waisted space when Mirador is opened and need to scroll to have the entire Mirador window
![image](https://github.com/user-attachments/assets/a9e7709a-f3b3-4720-b3d2-afcfbf63ccd2)

**Comment by Drilio** [comment]
@daxid  "Images are shown as videos in the media panel and in the media tab" are you sure ? I don't have the bug on my instance and you screen display placeholder with the videos logo

**Comment by daxid** [comment]
@Drilio , you can see on the screenshot that the first one is a PNG file, not a video.

However, you are right, things look OK for newly created media. The problem must be for old media only, so just let it be :-)

**Comment by Drilio** [comment]
I have an issue to make mirador resize mirador page cause of mirador code : 
Here is the best working I can do : 
![Image](https://github.com/user-attachments/assets/5d7065e2-6d41-4327-8494-72ba8a993805)
but you can roll down a bit : 
![Image](https://github.com/user-attachments/assets/9b7aec33-2f05-4215-ba3e-421d814a60a9)

I tried many things but when I reduce the size of the mirador container or mirador itself it result on this : 
![Image](https://github.com/user-attachments/assets/933edc23-def9-40f2-8704-ca74e0233f5a)

as you can see there mirador is built in a way it overlap his own containers : 
![Image](https://github.com/user-attachments/assets/62278aa6-d3f9-4dbd-91b4-6e62906f8a77)
