### ISSUE TITLE
Config issue in prod mode 

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-multi-user#46]
when we try to create an account or connect : 

![Image](https://github.com/SCENE-CE/mirador-multi-user/assets/117070163/43cb5dd8-66ac-4f01-a25e-c902ea21c098)

**Comment by Drilio** [comment]
Error come from this line : https://github.com/SCENE-CE/mirador-multi-user/blob/ace9bd848d8190a7bd71ed070a3051b3d882d5de/frontend-TS/src/features/auth/api/register.ts#L27

**Comment by geourjoa** [comment]
Seem to be a config error.

When you see "JSON.parse error" on error related to backend connection, it's often relevant to check more information in the network tab in browser dev tools

**Comment by geourjoa** [comment]
I will deploy and check

**Comment by geourjoa** [comment]
It's again the sed scrypt failing in frontend entrypoint. So the config.ts is not set
