### ISSUE TITLE
Add mail support in backend

### ISSUE THREAD

**Issue by geourjoa** [SCENE-CE/mirador-multi-user#49]
We want to support basic mail function : 

- [x] Reset password
- [x] Account created with link of confirmation- [ ] 
- [ ] _Someone_ share you _something_ on  Arvest
- [x] notify admin if an error occur in arvest backend

**Comment by geourjoa** [comment]
@Drilio 

Can you update the list of features achieved?

**Comment by Drilio** [comment]
see https://github.com/SCENE-CE/mirador-multi-user/issues/271
and https://github.com/SCENE-CE/mirador-multi-user/issues/219

**Comment by Drilio** [comment]
Share mailing isn't in the specs
