### ISSUE TITLE
[Demo] : Media not scaled in Mirador

### ISSUE THREAD

**Issue by daxid** [SCENE-CE/mirador-multi-user#53]
## In https://scene.tetras-libre.fr/ : 

1. Open manifests in Mirador, for instance: 
  - https://files.tetras-libre.fr/manifests/re_walden_cut.json
  - https://files.tetras-libre.fr/manifests/walden_nouvel2_manifest.json
3. Reduce the place available for the vide ether : 
  - by opening the info panel on the left
  - by reducing the navigator window
  - or by opening several manifests in the same workspace
4. See that the media are scaled down to fit in available space (both video and image):

![image](https://github.com/SCENE-CE/mirador-multi-user/assets/12066206/c8848bff-969b-4397-8f23-a90d2e4ba3b9)

## In https://arvest.tetras-libre.fr :

Do the same 1 and 2

3. See that media are not scaled down. This makes any demo pretty much impossible in Arvest:

![image](https://github.com/SCENE-CE/mirador-multi-user/assets/12066206/8047a486-2c54-4273-9920-20f5d007f50e)

**Comment by daxid** [comment]
I see that media are not scaled down either on https://preprod-scene.tetras-libre.fr/

Therefore the problem comes from late developments made on Mirador Video to try to improve the annotation alignments.

@geourjoa Please rollback the Mirador version used in Arvest to the same that is used in https://scene.tetras-libre.fr/

This should fix the scaling problem, but regress on the annotation alignment side. This is a trade of we have to make, otherwise any demo is basically impossible.

**Comment by geourjoa** [comment]
Fix deployed
